Project1VS/force-app/main/default/objects/Character__c/Character__c.object-meta.xml
<CustomObject>
    <description>Record of all Characters within the games available</description>
    <label>Character</label>
    <nameField>
        <label>Character Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Characters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project1VS/force-app/main/default/objects/Character__c/fields/In_Party__c.field-meta.xml
<CustomField>
    <fullName>In_Party__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>In Party</label>
    <referenceTo>Party__c</referenceTo>
    <relationshipLabel>Characters</relationshipLabel>
    <relationshipName>Characters</relationshipName>
    <type>Lookup</type>
</CustomField>

Project1VS/force-app/main/default/objects/Character__c/fields/Party__c.field-meta.xml
<CustomField>
    <fullName>Party__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Party</label>
    <referenceTo>Party__c</referenceTo>
    <relationshipLabel>Characters</relationshipLabel>
    <relationshipName>Characters</relationshipName>
    <type>Lookup</type>
</CustomField>

Project1VS/force-app/main/default/objects/Character__c/fields/Used_By__c.field-meta.xml
<CustomField>
    <fullName>Used_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Used By</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>equals</operation>
            <value>D&amp;DU - Player</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Characters</relationshipName>
    <type>Lookup</type>
</CustomField>

Project1VS/force-app/main/default/objects/DnDCampaign__c/DnDCampaign__c.object-meta.xml
<CustomObject>
    <label>DnDCampaign</label>
    <nameField>
        <displayFormat>dndcampaign-{0000}</displayFormat>
        <label>DnDCampaign Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DnDCampaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project1VS/force-app/main/default/objects/DnDCampaign__c/fields/Campaign_Name__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Name__c</fullName>
    <label>Campaign Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Project1VS/force-app/main/default/objects/DnDCampaign__c/fields/Dungeon_Master__c.field-meta.xml
<CustomField>
    <fullName>Dungeon_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dungeon Master</label>
    <referenceTo>User</referenceTo>
    <relationshipName>DnDCampaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

Project1VS/force-app/main/default/objects/Party__c/Party__c.object-meta.xml
<CustomObject>
    <label>Party</label>
    <nameField>
        <label>Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project1VS/force-app/main/default/classes/ptyPgExtender.cls
public class ptyPgExtender {
    
    //Most of the controller's functionality is in here, rather than in the actual controller.
    //Because it's in an extension, it runs in user context, rather than system context.
    //This will be important when we query parties.
    public String selectedParty{get;set;}
    public String partyName{get;set;}
    
    
    
    public ptyPgExtender(partyPageController ppc) {
        selectedParty = null;
        partyName = null;
        getPartyList();
        getChars();
        getPlayas();
        getCpaign();
    }
    
    public List<Party__c> getPartyList() {
        //This looks like it will display every single party. But since we're in system context, it'll take into account
        //the user's security settings. So any user who visits here won't be able to see any parties that they don't
        //have access to.
        return [SELECT name FROM party__c];
    }
    
    // This method fires when you click on an item in the "Party" table. It should show:
    // 1. The charactesrs in the party
    // 2. The players pertaining to each character
    // 3. The campaign the party is in
    // 4. The Dungeon Master for this campaign
    // Is it time to use a wrapped class?
    public void selectParty() {
        partyName = String.valueOf([SELECT name FROM party__c WHERE id =: selectedParty LIMIT 1]);
    }
    
    public List<Character__c> getChars() {
        List<Character__c> charList = new List<Character__c>();
        
        if (selectedParty != null) {
        	charList = [SELECT name FROM character__c where in_party__c =: selectedParty];
        } else {
            charList = null;
        }
        
        return charList;
    }
    
    public List<Character__c> getPlayas() {
        return [SELECT used_by__c, name, in_party__c FROM character__c WHERE in_party__c =: selectedParty ];
       
    }
    
    public List<DndCampaign__c> getCpaign() {
        return [SELECT campaign_name__c, dungeon_master__c FROM DndCampaign__c where party__c =: selectedParty];
    }
    
    
}