Project1VS/force-app/main/default/objects/Character__c/Character__c.object-meta.xml
<CustomObject>
    <description>Record of all Characters within the games available</description>
    <label>Character</label>
    <nameField>
        <label>Character Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Characters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project1VS/force-app/main/default/objects/Character__c/fields/In_Party__c.field-meta.xml
<CustomField>
    <fullName>In_Party__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>In Party</label>
    <referenceTo>Party__c</referenceTo>
    <relationshipLabel>Characters</relationshipLabel>
    <relationshipName>Characters</relationshipName>
    <type>Lookup</type>
</CustomField>

Project1VS/force-app/main/default/objects/Character__c/fields/Party__c.field-meta.xml
<CustomField>
    <fullName>Party__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Party</label>
    <referenceTo>Party__c</referenceTo>
    <relationshipLabel>Characters</relationshipLabel>
    <relationshipName>Characters</relationshipName>
    <type>Lookup</type>
</CustomField>

Project1VS/force-app/main/default/objects/DnDCampaign__c/DnDCampaign__c.object-meta.xml
<CustomObject>
    <label>DnDCampaign</label>
    <nameField>
        <displayFormat>dndcampaign-{0000}</displayFormat>
        <label>DnDCampaign Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DnDCampaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project1VS/force-app/main/default/objects/DnDCampaign__c/fields/Realm__c.field-meta.xml
<CustomField>
    <fullName>Realm__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Realm</label>
    <referenceTo>Realm__c</referenceTo>
    <relationshipLabel>DnDCampaigns</relationshipLabel>
    <relationshipName>DnDCampaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

Project1VS/force-app/main/default/objects/DnDCampaign__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Region</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Region__c.In_Realm__c</field>
            <operation>equals</operation>
            <valueField>$Source.Realm__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Region__c</referenceTo>
    <relationshipLabel>DnDCampaigns</relationshipLabel>
    <relationshipName>DnDCampaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

Project1VS/force-app/main/default/objects/Party__c/Party__c.object-meta.xml
<CustomObject>
    <label>Party</label>
    <nameField>
        <label>Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project1VS/force-app/main/default/objects/Party__c/fields/Realm__c.field-meta.xml
<CustomField>
    <fullName>Realm__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Realm</label>
    <referenceTo>Realm__c</referenceTo>
    <relationshipLabel>Parties</relationshipLabel>
    <relationshipName>Parties</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Project1VS/force-app/main/default/objects/Party__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Region</label>
    <referenceTo>Region__c</referenceTo>
    <relationshipLabel>Parties</relationshipLabel>
    <relationshipName>Parties</relationshipName>
    <type>Lookup</type>
</CustomField>

Project1VS/force-app/main/default/objects/Player__c/fields/Realm__c.field-meta.xml
<CustomField>
    <fullName>Realm__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Realm</label>
    <referenceTo>Realm__c</referenceTo>
    <relationshipLabel>Players</relationshipLabel>
    <relationshipName>Players</relationshipName>
    <type>Lookup</type>
</CustomField>

Project1VS/force-app/main/default/objects/Player__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Region</label>
    <referenceTo>Region__c</referenceTo>
    <relationshipLabel>Players</relationshipLabel>
    <relationshipName>Players</relationshipName>
    <type>Lookup</type>
</CustomField>

Project1VS/force-app/main/default/objects/Realm__c/Realm__c.object-meta.xml
<CustomObject>
    <label>Realm</label>
    <nameField>
        <label>Realm Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Realms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project1VS/force-app/main/default/objects/Region__c/Region__c.object-meta.xml
<CustomObject>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project1VS/force-app/main/default/objects/Region__c/fields/Realm__c.field-meta.xml
<CustomField>
    <fullName>Realm__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Realm</label>
    <referenceTo>Realm__c</referenceTo>
    <relationshipLabel>Regions</relationshipLabel>
    <relationshipName>Regions</relationshipName>
    <type>Lookup</type>
</CustomField>

Project1VS/force-app/main/default/classes/partyPageController.cls
public class partyPageController {
    
    public List<Party__c> partyList{get;set;}
    public List<Character__c> charList{get;set;}
    public List<Player__c> playas{get;set;}
    public DnDCampaign__c camp{get;set;}
    public Party__c selectedParty{get;set;}
    
    public partyPageController() {
        getPartyList();
    }
    
    public void getPartyList() {
        partyList = [SELECT name, realm__c, region__c, (select name FROM characters__r) FROM party__c];
    }
    
    // This method fires when you click on an item in the "Party" table. It should show:
    // 1. The characters in the party
    // 2. The players pertaining to each character
    // 3. The campaign the party is in
    // 4. The Dungeon Master for this campaign
    // Is it time to use a wrapped class?
    public void additionalInfo() {
        getChars();
        getPlayas();
        getCampaign();
    }
    
    public void getChars() {
        
    }
    
    public void getPlayas() {
        
    }
    
    public void getCampaign() {
        
    }
    
    public void getDM() {
        
    }
    
}